/**
 * @file key.js
 * @author Kjetil Fossheim
 * @type {Object}
 * Test key used for debuging
 */


export default keyObj = {
  id: 1,
  title: 'Sneller',
  description: 'sneller er fine ting',
  level: 'null',
  keyStatus: 'prod',
  version: 1.2,
  keyWeb: 'sneller',
  content: {
    species: [
      {speciesId: 12, latinName:'Equisetum arvense', localName:'Åkersnelle', speciesText:'NA', order:'Equisetales', family:'Equiseaceae', gbiffID:'0', keyId: 1, spesialKey: 0 },
      {speciesId: 13, latinName:'Equisetum fluviatile', localName:'Elvesnelle', speciesText:'NA', order:'Equisetales', family:'Equiseaceae', gbiffID:'0', keyId: 1, spesialKey: 0 },
      {speciesId: 14, latinName:'Equisetum hyemale', localName:'Skavgras', speciesText:'NA', order:'Equisetales', family:'Equiseaceae', gbiffID:'0', keyId: 1, spesialKey: 0 },
      {speciesId: 15, latinName:'Equisetum palustre', localName:'Myrsnelle', speciesText:'NA', order:'Equisetales', family:'Equiseaceae', gbiffID:'0', keyId: 1, spesialKey: 0 },
      {speciesId: 16, latinName:'Equisetum pratense', localName:'Engsnelle', speciesText:'NA', order:'Equisetales', family:'Equiseaceae', gbiffID:'0', keyId: 1, spesialKey: 0 },
      {speciesId: 17, latinName:'Equisetum scirpoides', localName:'Dvergsnelle', speciesText:'NA', order:'Equisetales', family:'Equiseaceae', gbiffID:'0', keyId: 1, spesialKey: 0 },
      {speciesId: 18, latinName:'Equisetum sylvaticum', localName:'Skogsnelle', speciesText:'NA', order:'Equisetales', family:'Equiseaceae', gbiffID:'0', keyId: 1, spesialKey: 0 },
      {speciesId: 19, latinName:'Equisetum variegatum', localName:'Fjellsnelle', speciesText:'NA', order:'Equisetales', family:'Equiseaceae', gbiffID:'0', keyId: 1, spesialKey: 0 },
    ],
    trait: [
      {traitId: 9, traitText:'Strobilus', important:0, keyId: 1 },
      {traitId: 10, traitText:'Grener', important:0, keyId: 1 },
      {traitId: 11, traitText:'Stengel 1', important:0, keyId: 1 },
      {traitId: 12, traitText:'Stengel 2', important:0, keyId: 1 },
      {traitId: 13, traitText:'Størrelse', important:0, keyId: 1 },
      {traitId: 14, traitText:'Bladtenner', important:0, keyId: 1 },
      {traitId: 15, traitText:'Vokseplass', important:0, keyId: 1 }
    ],
    value:[
      {valueId: 21, valueText:'På sommerstengel', valueInfo: 'NA', traitId:9, keyId: 1 },
      {valueId: 22, valueText:'På egen vårstengel (uten grener)', valueInfo: 'NA', traitId:9, keyId: 1 },
      {valueId: 23, valueText:'Uten/få grener', valueInfo: 'NA', traitId:10, keyId: 1 },
      {valueId: 24, valueText:'Enkle grener', valueInfo: 'NA', traitId:10, keyId: 1 },
      {valueId: 25, valueText:'Grener på grener', valueInfo: 'NA', traitId:10, keyId: 1 },
      {valueId: 26, valueText:'Ru', valueInfo: 'NA', traitId:11, keyId: 1 },
      {valueId: 27, valueText:'Glatt', valueInfo: 'NA', traitId:11, keyId: 1 },
      {valueId: 28, valueText:'Myk (ettårig)', valueInfo: 'NA', traitId:12, keyId: 1 },
      {valueId: 29, valueText:'Hard (flerårig)', valueInfo: 'NA', traitId:12, keyId: 1 },
      {valueId: 30, valueText:'Opp til 15 cm', valueInfo: 'NA', traitId:13, keyId: 1 },
      {valueId: 31, valueText:'15-40 cm', valueInfo: 'NA', traitId:13, keyId: 1 },
      {valueId: 32, valueText:'40-100 cm', valueInfo: 'NA', traitId:13, keyId: 1 },
      {valueId: 33, valueText:'Opp til 10', valueInfo: 'NA', traitId:14, keyId: 1 },
      {valueId: 34, valueText:'Over 10', valueInfo: 'NA', traitId:14, keyId: 1 },
      {valueId: 35, valueText:'Fjell', valueInfo: 'NA', traitId:15, keyId: 1 },
      {valueId: 36, valueText:'Vann', valueInfo: 'NA', traitId:15, keyId: 1 },
      {valueId: 37, valueText:'Skog/eng', valueInfo: 'NA', traitId:15, keyId: 1 },
      {valueId: 38, valueText:'Myr', valueInfo: 'NA', traitId:15, keyId: 1 }
    ],
    spHasValue: [
      {spHasValueId: 95, spId: 12, valueId: 22, keyId: 1 },
      {spHasValueId: 96, spId: 12, valueId: 24, keyId: 1 },
      {spHasValueId: 97, spId: 12, valueId: 27, keyId: 1 },
      {spHasValueId: 98, spId: 12, valueId: 28, keyId: 1 },
      {spHasValueId: 99, spId: 12, valueId: 31, keyId: 1 },
      {spHasValueId: 100, spId: 12, valueId: 33, keyId: 1 },
      {spHasValueId: 101, spId: 12, valueId: 36, keyId: 1 },
      {spHasValueId: 102, spId: 12, valueId: 37, keyId: 1 },
      {spHasValueId: 103, spId: 12, valueId: 38, keyId: 1 },
      {spHasValueId: 104, spId: 13, valueId: 21, keyId: 1 },
      {spHasValueId: 105, spId: 13, valueId: 23, keyId: 1 },
      {spHasValueId: 106, spId: 13, valueId: 24, keyId: 1 },
      {spHasValueId: 107, spId: 13, valueId: 27, keyId: 1 },
      {spHasValueId: 108, spId: 13, valueId: 28, keyId: 1 },
      {spHasValueId: 109, spId: 13, valueId: 32, keyId: 1 },
      {spHasValueId: 110, spId: 13, valueId: 34, keyId: 1 },
      {spHasValueId: 111, spId: 13, valueId: 35, keyId: 1 },
      {spHasValueId: 112, spId: 13, valueId: 38, keyId: 1 },
      {spHasValueId: 113, spId: 14, valueId: 21, keyId: 1 },
      {spHasValueId: 114, spId: 14, valueId: 23, keyId: 1 },
      {spHasValueId: 115, spId: 14, valueId: 26, keyId: 1 },
      {spHasValueId: 116, spId: 14, valueId: 29, keyId: 1 },
      {spHasValueId: 117, spId: 14, valueId: 31, keyId: 1 },
      {spHasValueId: 118, spId: 14, valueId: 32, keyId: 1 },
      {spHasValueId: 119, spId: 14, valueId: 34, keyId: 1 },
      {spHasValueId: 120, spId: 14, valueId: 37, keyId: 1 },
      {spHasValueId: 121, spId: 14, valueId: 38, keyId: 1 },
      {spHasValueId: 122, spId: 15, valueId: 22, keyId: 1 },
      {spHasValueId: 123, spId: 15, valueId: 23, keyId: 1 },
      {spHasValueId: 124, spId: 15, valueId: 24, keyId: 1 },
      {spHasValueId: 125, spId: 15, valueId: 27, keyId: 1 },
      {spHasValueId: 126, spId: 15, valueId: 28, keyId: 1 },
      {spHasValueId: 127, spId: 15, valueId: 30, keyId: 1 },
      {spHasValueId: 128, spId: 15, valueId: 31, keyId: 1 },
      {spHasValueId: 129, spId: 15, valueId: 33, keyId: 1 },
      {spHasValueId: 130, spId: 15, valueId: 37, keyId: 1 },
      {spHasValueId: 131, spId: 15, valueId: 38, keyId: 1 },
      {spHasValueId: 132, spId: 16, valueId: 22, keyId: 1 },
      {spHasValueId: 133, spId: 16, valueId: 24, keyId: 1 },
      {spHasValueId: 134, spId: 16, valueId: 26, keyId: 1 },
      {spHasValueId: 135, spId: 16, valueId: 28, keyId: 1 },
      {spHasValueId: 136, spId: 16, valueId: 30, keyId: 1 },
      {spHasValueId: 137, spId: 16, valueId: 31, keyId: 1 },
      {spHasValueId: 138, spId: 16, valueId: 33, keyId: 1 },
      {spHasValueId: 139, spId: 16, valueId: 37, keyId: 1 },
      {spHasValueId: 140, spId: 17, valueId: 21, keyId: 1 },
      {spHasValueId: 141, spId: 17, valueId: 23, keyId: 1 },
      {spHasValueId: 142, spId: 17, valueId: 26, keyId: 1 },
      {spHasValueId: 143, spId: 17, valueId: 29, keyId: 1 },
      {spHasValueId: 144, spId: 17, valueId: 30, keyId: 1 },
      {spHasValueId: 145, spId: 17, valueId: 31, keyId: 1 },
      {spHasValueId: 146, spId: 17, valueId: 33, keyId: 1 },
      {spHasValueId: 147, spId: 17, valueId: 35, keyId: 1 },
      {spHasValueId: 148, spId: 18, valueId: 21, keyId: 1 },
      {spHasValueId: 149, spId: 18, valueId: 25, keyId: 1 },
      {spHasValueId: 150, spId: 18, valueId: 27, keyId: 1 },
      {spHasValueId: 151, spId: 18, valueId: 28, keyId: 1 },
      {spHasValueId: 152, spId: 18, valueId: 31, keyId: 1 },
      {spHasValueId: 153, spId: 18, valueId: 33, keyId: 1 },
      {spHasValueId: 154, spId: 18, valueId: 37, keyId: 1 },
      {spHasValueId: 155, spId: 19, valueId: 21, keyId: 1 },
      {spHasValueId: 156, spId: 19, valueId: 23, keyId: 1 },
      {spHasValueId: 157, spId: 19, valueId: 26, keyId: 1 },
      {spHasValueId: 158, spId: 19, valueId: 29, keyId: 1 },
      {spHasValueId: 159, spId: 19, valueId: 30, keyId: 1 },
      {spHasValueId: 160, spId: 19, valueId: 33, keyId: 1 },
      {spHasValueId: 161, spId: 19, valueId: 35, keyId: 1 },
      {spHasValueId: 162, spId: 19, valueId: 37, keyId: 1 },
      {spHasValueId: 163, spId: 19, valueId: 3, keyId: 1 }
    ],
    image: [
      {imageId: 1, type:'v', typeId:21, image:'url.png', keyId: 1 },
      {imageId: 3, type:'v', typeId:23, image:'url2.png', keyId: 1 },
      {imageId: 2, type:'s', typeId:12, image:'test.png', keyId: 1 }
    ],
    traitEliminate: [
      {traitId: 15, valueId: 22, keyId: 1 }
    ]
  },
};
